[workspace]

[package]
name = "crane-wyoming"
version = "0.1.0"
description = "Self-hosted voice services for Home Assistant"
edition = "2024"
license = "MIT"
repository = "https://github.com/cryptomilk/crane-wyoming"
authors = ["Andreas Schneider <asn@cryptomilk.org>"]

[lib]
name = "crane_wyoming"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
blake3 = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["io-util", "sync", "net", "rt-multi-thread", "macros", "signal", "time"] }
tracing = "0.1"
tracing-subscriber = "0.3"
crane = { git = "https://github.com/cryptomilk/Crane", branch = "asn-refactor" }
crane-core = { git = "https://github.com/cryptomilk/Crane", branch = "asn-refactor" }
# Must match the candle-core version
candle-core = "0.10.2"

[dev-dependencies]
tempfile = "3"

[features]
cuda = ["crane/cuda"]
cudnn = ["crane/cudnn"]
mkl = ["crane/mkl"]
