when:
  - event: pull_request
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  test:
    image: registry.opensuse.org/home/gladiac/container/containers/codeberg-rust:latest
    environment:
      CARGO_TERM_COLOR: always
      SCCACHE_CACHE_SIZE: "1G"
      RUSTC_WRAPPER: sccache
      CARGO_INCREMENTAL: "0"
    commands:
      - export CARGO_HOME="`pwd`/build-cache/cargo"
      - export SCCACHE_DIR="`pwd`/build-cache/sccache"
      - mkdir -p "$SCCACHE_DIR"
      - cargo fmt --check
      - cargo build
      - cargo clippy -- -W clippy::pedantic -D warnings
      - cargo test
      - sccache --show-stats

  cargo-deny:
    image: registry.opensuse.org/home/gladiac/container/containers/codeberg-rust:latest
    environment:
      CARGO_TERM_COLOR: always
      SCCACHE_CACHE_SIZE: "1G"
      RUSTC_WRAPPER: sccache
      CARGO_INCREMENTAL: "0"
    commands:
      - export CARGO_HOME="`pwd`/build-cache/cargo"
      - export SCCACHE_DIR="`pwd`/build-cache/sccache"
      - cargo deny check
