[package]
name = "crane-wyoming"
version = "0.1.0"
description = "Self-hosted voice services for Home Assistant"
edition = "2024"
license = "GPL-2.0-or-later"
repository = "https://github.com/cryptomilk/crane-wyoming"
authors = ["Andreas Schneider <asn@cryptomilk.org>"]
publish = false

[lib]
name = "crane_wyoming"
path = "src/lib.rs"

[dependencies]
wyoming-protocol = { path = "../wyoming-protocol" }
anyhow = "1"
blake3 = "1"
clap = { version = "4", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["io-util", "sync", "net", "rt-multi-thread", "macros", "signal", "time"] }
tracing = "0.1"
tracing-subscriber = "0.3"
crane = { git = "https://github.com/lucasjinreal/Crane", rev = "a1703934549d27cbe27ef848f3f4802c6ebc12e6" }
crane-core = { git = "https://github.com/lucasjinreal/Crane", rev = "a1703934549d27cbe27ef848f3f4802c6ebc12e6" }
# Keep in sync with Crane
candle-core = "0.11"

[dev-dependencies]
tempfile = "3"

[features]
cuda = ["crane/cuda"]
cudnn = ["crane/cudnn"]
mkl = ["crane/mkl"]
